export const IPC_CHANNELS = {
  GET_SNAPSHOT: "app:get-snapshot",
  OPEN_SOURCE: "app:open-source",
  OPEN_SOURCE_PATH: "app:open-source-path",
  OPEN_RECENT_SOURCE: "app:open-recent-source",
  OPEN_EXTERNAL_URL: "app:open-external-url",
  GET_SERVICE_LOGS: "app:get-service-logs",
  GET_SERVICE_STATS: "app:get-service-stats",
  UPDATE_SETTINGS: "app:update-settings",
  CLEAR_RECENTS: "app:clear-recents",
  RUN_PROJECT_ACTION: "app:run-project-action",
  BUILD_EVENT: "build:event",
  UPDATE_PROJECT_CONFIG_FILES: "app:update-project-config-files",
  READ_SOURCE_FILE: "app:read-source-file",
  SAVE_SOURCE_FILE: "app:save-source-file",
  SEARCH_DOCKER_HUB: "app:search-docker-hub",
  ADD_SERVICE_TO_PROJECT: "app:add-service-to-project",
  REMOVE_SERVICE_FROM_PROJECT: "app:remove-service-from-project",
  SNAPSHOT_EVENT: "snapshot:event",
  NETWORK_GET_TOPOLOGY: "network:get-topology",
  NETWORK_RUN_ACTION: "network:run-action",
  REMOTE_ACCESS_GET_STATUS: "remote-access:get-status",
  REMOTE_ACCESS_ENABLE: "remote-access:enable",
  REMOTE_ACCESS_DISABLE: "remote-access:disable",
  REMOTE_ACCESS_REGENERATE_TOKEN: "remote-access:regenerate-token",
  REMOTE_ACCESS_SET_HOST: "remote-access:set-host",
  COPY_TO_CLIPBOARD: "app:copy-to-clipboard"
} as const;
